//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerOption
    {
        public int AnswerOptionsID { get; set; }
        public int ObjectiveTestID { get; set; }
        public string AnswerOptionsDescription { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ObjectiveTest ObjectiveTest { get; set; }
    }
}
