//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableSeatsForSlot
    {
        public int AvailableSeatsForSlotsId { get; set; }
        public Nullable<int> AvailableDatesId { get; set; }
        public Nullable<int> SlotId { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> RemainingSeats { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual AvailableDate AvailableDate { get; set; }
        public virtual ExamSlot ExamSlot { get; set; }
    }
}
