//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CandidateDetail()
        {
            this.CandidateExamBookingDetails = new HashSet<CandidateExamBookingDetail>();
            this.CandidateVerifications = new HashSet<CandidateVerification>();
            this.ExamResults = new HashSet<ExamResult>();
            this.Testimonials = new HashSet<Testimonial>();
        }
    
        public int CandidateId { get; set; }
        public string ExamId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<bool> EmailApproved { get; set; }
        public string Phone { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string PostCode { get; set; }
        public string DrivingLicenseNumber { get; set; }
        public string IPAddress { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ExaminerId { get; set; }
        public string uniquetoken { get; set; }
        public Nullable<bool> ExamAttended { get; set; }
        public Nullable<bool> FrontCamera { get; set; }
        public Nullable<bool> BackCamera { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExamBookingDetail> CandidateExamBookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateVerification> CandidateVerifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamResult> ExamResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Testimonial> Testimonials { get; set; }
    }
}
