//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateVerification
    {
        public int VerificaitonId { get; set; }
        public int CandidateId { get; set; }
        public bool Photo { get; set; }
        public bool DrivingLicense { get; set; }
        public bool FrontCamera { get; set; }
        public bool Microphone { get; set; }
        public bool BackCamera { get; set; }
        public bool LipMovement { get; set; }
        public bool EligibleForStartExam { get; set; }
        public int VerifiedBy { get; set; }
        public System.DateTime VerifiedOn { get; set; }
    
        public virtual ExaminerDetail ExaminerDetail { get; set; }
        public virtual CandidateDetail CandidateDetail { get; set; }
    }
}
