//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyDetail()
        {
            this.JobDetails = new HashSet<JobDetail>();
            this.JobSubmissionDetails = new HashSet<JobSubmissionDetail>();
        }
    
        public int CompanyId { get; set; }
        public string UserId { get; set; }
        public string CompanyName { get; set; }
        public string AddressLIne1 { get; set; }
        public string AddressLIne2 { get; set; }
        public string AddressLIne3 { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Position { get; set; }
        public string CompanyLogo { get; set; }
        public string NatureofBusiness { get; set; }
        public string CompanySize { get; set; }
        public Nullable<bool> Status { get; set; }
        public string RoleType { get; set; }
        public string AboutTheCompany { get; set; }
        public string DetailedDescriptionAboutCompany { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDetail> JobDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSubmissionDetail> JobSubmissionDetails { get; set; }
    }
}
