//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobDetail()
        {
            this.JobSubmissionDetails = new HashSet<JobSubmissionDetail>();
        }
    
        public int JobId { get; set; }
        public int CompanyId { get; set; }
        public string JobTile { get; set; }
        public string Location { get; set; }
        public string Fees { get; set; }
        public string JobDescription { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public string NatureOfWork { get; set; }
        public string JobDetailsAttachmentUrl { get; set; }
        public string ExpectedDuration { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastDateToApply { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSubmissionDetail> JobSubmissionDetails { get; set; }
    }
}
