//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSubmissionDetail
    {
        public int JobSubmissionId { get; set; }
        public int JobId { get; set; }
        public int CompanyId { get; set; }
        public string CoveringLetter { get; set; }
        public string ProfileAttachmentUrl { get; set; }
        public Nullable<bool> PIInsurance { get; set; }
        public Nullable<bool> PLInsurance { get; set; }
        public string AssociationMembership { get; set; }
        public string SimilarJobExperience { get; set; }
        public string ProposedFees { get; set; }
        public string EstimatedTimeOfCompletion { get; set; }
        public string ProjectReference { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
        public virtual JobDetail JobDetail { get; set; }
    }
}
