//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectiveTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjectiveTest()
        {
            this.AnswerOptions = new HashSet<AnswerOption>();
        }
    
        public int ObjectiveTestID { get; set; }
        public string Question { get; set; }
        public string QuestionImage { get; set; }
        public int QuestionTypeId { get; set; }
        public int CorrectAnswerID { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Answered { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> ImageShow { get; set; }
        public Nullable<int> AllowedTime { get; set; }
        public string Priority { get; set; }
        public string VideoLink { get; set; }
        public Nullable<bool> VideoShow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerOption> AnswerOptions { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
