//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoScore
    {
        public int ScoreID { get; set; }
        public int VideoID { get; set; }
        public decimal TimeInterval { get; set; }
        public string MouseClick { get; set; }
        public string KeyboardPress { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual VideoType VideoType { get; set; }
    }
}
